INSERT INTO cards (id, name, element, power, color) VALUES
-- FIRE
('f1',  'Llama Débil',       'fire',  1,  'red'),
('f2',  'Chispa',            'fire',  2,  'orange'),
('f3',  'Brasas',            'fire',  3,  'yellow'),
('f4',  'Hoguera',           'fire',  4,  'red'),
('f5',  'Llamarada',         'fire',  5,  'orange'),
('f6',  'Fuego Medio',       'fire',  6,  'purple'),
('f7',  'Torbellino',        'fire',  7,  'blue'),
('f8',  'Incendio',          'fire',  8,  'green'),
('f9',  'Volcán',            'fire',  9,  'red'),
('f10', 'Magma',             'fire',  10, 'orange'),
('f11', 'Erupción',          'fire',  11, 'yellow'),
('f12', 'Dragón de Fuego',   'fire',  12, 'red'),
-- WATER
('w1',  'Gota',              'water', 1,  'blue'),
('w2',  'Charco',            'water', 2,  'green'),
('w3',  'Riachuelo',         'water', 3,  'yellow'),
('w4',  'Corriente',         'water', 4,  'blue'),
('w5',  'Ola',               'water', 5,  'purple'),
('w6',  'Torrente',          'water', 6,  'red'),
('w7',  'Marea',             'water', 7,  'green'),
('w8',  'Tifón',             'water', 8,  'orange'),
('w9',  'Maremoto',          'water', 9,  'blue'),
('w10', 'Tormenta',          'water', 10, 'purple'),
('w11', 'Huracán',           'water', 11, 'red'),
('w12', 'Tsunami',           'water', 12, 'blue'),
-- SNOW
('s1',  'Copo',              'snow',  1,  'blue'),
('s2',  'Escarcha',          'snow',  2,  'white'),
('s3',  'Bola de Nieve',     'snow',  3,  'green'),
('s4',  'Ventisca Leve',     'snow',  4,  'yellow'),
('s5',  'Nieve Densa',       'snow',  5,  'blue'),
('s6',  'Hielo',             'snow',  6,  'purple'),
('s7',  'Glaciar',           'snow',  7,  'red'),
('s8',  'Ventisca',          'snow',  8,  'orange'),
('s9',  'Tormenta Ártica',   'snow',  9,  'blue'),
('s10', 'Blizzard',          'snow',  10, 'green'),
('s11', 'Avalancha',         'snow',  11, 'yellow'),
('s12', 'Cataclismo Gélido', 'snow',  12, 'blue');